### ISSUE TITLE
Balance issue on wind generator

### ISSUE THREAD

**Issue by 3TUSK** [LambdaInnovation/AcademyCraft-feedback#3]
刚刚看完了TileWindGenerator的代码，感觉输出功率的算法好像只是统计6x6x6范围内的空气方块总数...这是不是意味着可以在地下放一排风力发电机就可以获取大量能源...？雷暴天气下270EU/t的功率已经超越很多其他科技mod的风力发电机了...（这种赶超核电的感觉是怎么回事？）
Whatever，我不是很确定我对代码的理解是正确的...但是还是想通过这个issue证实一下...

**Comment by KSkun** [comment]
WindGen在本β版本中并未添加，所以对于算法的维护还没有进行，具体事项请联系该类开发者[WeAthFolD]
